package ViewModel;
import Entities.Playlist;
import Entities.RegularUser;
import Entities.User;
import Entities.Song;
import Presenter.playlistPresenter;
import Controller.newPlaylistController;
import UseCase.CreatePlaylistInteractor;
import Controller.EditPlaylistController;
import UseCase.EditPlaylistInteractor;
import ViewModel.UserDsView;
import View.InMemoryUser;

public class playlistViewModel {
    private final playlistPresenter playlistPresenter;
    private String outputMessage;

    private final newPlaylistController newPlaylistController;

    private final EditPlaylistController editPlaylistController;

    private PlaylistDsView currPlaylist;

    public playlistViewModel(){
        // get necessary information from View to construct a new playlist
        //TODO: This is the controller, just pass this to the controller, move to controller
        //TODO: Create controller once in the view as an instance variable / pass as a parameter in main

        //Blank output data object to extract success message from
        //sets its presenter to itself
        this.playlistPresenter = new playlistPresenter(this);

        this.newPlaylistController = new newPlaylistController(new CreatePlaylistInteractor(playlistPresenter));

        this.editPlaylistController = new EditPlaylistController(new EditPlaylistInteractor(playlistPresenter));
    }
    public void setOutputMessage(String message){
        this.outputMessage = message;
    }

    //TODO: keeping this uncommented just in case I may need it later, but will delete in a future push
//    /**
//     *
//     * @param id ID given by view
//     * @param user User object given by view
//     * @param playlistName playlist name given by view
//     *  Overloaded method for creating an empty playlist
//     */
//    public playlistViewModel(int id, RegularUser user, String playlistName){
//        // get necessary information from View to construct a new playlist
//        newPlaylistInputData inputData = new newPlaylistInputData(id,playlistName,user);
//        //Blank output data object to extract success message from
//        this.playlistPresenter = new playlistPresenter(this);
////        this.newPlaylistController = new newPlaylistController(inputData,playlistPresenter);
//    }

    /**
     * @return output message generated by the Controller and update the presenter's outputMessage with it as well
     */

    public String callNewPlaylistUseCase(UserDsView user, String playlistName, Song firstSong){
        this.currPlaylist = this.newPlaylistController.createNewPlaylist(user,playlistName,firstSong);
        String msg = this.playlistPresenter.getOutputMessage();
        return msg;
    }

    public String callNewPlaylistUseCase(UserDsView user, String playlistName){
        this.currPlaylist = this.newPlaylistController.createNewPlaylist(user,playlistName);
        String msg = this.playlistPresenter.getOutputMessage();
        return msg;
    }

    public String callAddSong(UserDsView user, Playlist playlist, Song song){
        this.editPlaylistController.addSong(user,playlist,song);
        String msg = this.playlistPresenter.getOutputMessage();
        return msg;
    }
    public String callRemoveSong(UserDsView user, Playlist playlist, Song song){
        this.editPlaylistController.removeSong(user,playlist,song);
        String msg = this.playlistPresenter.getOutputMessage();
        return msg;
    }

    public PlaylistDsView getCurrPlaylist() {
        return currPlaylist;
    }

}
