package Presenter;
import OutputBoundary.newPlaylistOutputBoundary;
import OutputData.newPlaylistOutputData;
import ViewModel.playlistViewModel;

public class playlistPresenter implements newPlaylistOutputBoundary {

    private String outputMessage;

    final playlistViewModel viewModel;

    public playlistPresenter(playlistViewModel viewModel){
        //this.outputMessage = outputData.getCreatedMessage();
        this.viewModel = viewModel;
        this.outputMessage = "";
    }
    //TODO implement later & ask for help on. Also add editPlaylist stuff when I have better handle on output stuff
    //TODO: Remove later when implementation finalized
    public String getOutputMessage(){
        return outputMessage;
    }
    /**
     *
     * @return String confirming the creation of playlist generated by the createPlaylist Use case
     */

//    public String getPlaylistCreationConfirmation() {
//        return viewModel.callNewPlaylistUseCase();
//    }

    //TODO: Also change info in view model, make a method to set it to this in the view model,
    // make a new instnace attribute

    /**
     *
     * @param outputData outputData object containing confirmation message.
     */
    public void setPlaylistCreationConfirmation(newPlaylistOutputData outputData){
        this.outputMessage = outputData.getCreatedMessage();
        this.viewModel.setOutputMessage(this.outputMessage);
    }
}
