package Presenter;
import OutputBoundary.newPlaylistOutputBoundary;
import ViewModel.playlistViewModel;

public class playlistPresenter implements newPlaylistOutputBoundary {

    private String outputMessage;

    final playlistViewModel viewModel;

    public playlistPresenter(playlistViewModel viewModel){
        //this.outputMessage = outputData.getCreatedMessage();
        this.viewModel = viewModel;
        this.outputMessage = "";
    }

//    public void setOutputMessage(String newMessage){
//        this.outputMessage = newMessage;
//    }
    //TODO implement later & ask for help on. Also add editPlaylist stuff when I have better handle on output stuff
    public void setOutputMessage(String outputMessage){
        this.outputMessage = outputMessage;
    }
    public String getOutputMessage(){
        return outputMessage;
    }
    /**
     *
     * @return String confirming the creation of playlist generated by the createPlaylist Use case
     */
    public String getPlaylistCreationConfirmation() {
        return viewModel.callNewPlaylistUseCase();
    }
}
